package com.athena.backend.platform.utils;

import java.util.HashMap;

public class MimeTypeUtil {
	public static final String MIME_APPLICATION_ANDREW_INSET = "application/andrew-inset";
	public static final String MIME_APPLICATION_JSON = "application/json";
	public static final String MIME_APPLICATION_ZIP       = "application/zip";
	public static final String MIME_APPLICATION_X_GZIP      = "application/x-gzip";
	public static final String MIME_APPLICATION_TGZ       = "application/tgz";
	public static final String MIME_APPLICATION_MSWORD      = "application/msword";
	public static final String MIME_APPLICATION_POSTSCRIPT    = "application/postscript";
	public static final String MIME_APPLICATION_PDF       = "application/pdf";
	public static final String MIME_APPLICATION_JNLP      = "application/jnlp";
	public static final String MIME_APPLICATION_MAC_BINHEX40  = "application/mac-binhex40";
	public static final String MIME_APPLICATION_MAC_COMPACTPRO  = "application/mac-compactpro";
	public static final String MIME_APPLICATION_MATHML_XML    = "application/mathml+xml";
	public static final String MIME_APPLICATION_OCTET_STREAM  = "application/octet-stream";
	public static final String MIME_APPLICATION_ODA       = "application/oda";
	public static final String MIME_APPLICATION_RDF_XML     = "application/rdf+xml";
	public static final String MIME_APPLICATION_JAVA_ARCHIVE  = "application/java-archive";
	public static final String MIME_APPLICATION_RDF_SMIL    = "application/smil";
	public static final String MIME_APPLICATION_SRGS      = "application/srgs";
	public static final String MIME_APPLICATION_SRGS_XML    = "application/srgs+xml";
	public static final String MIME_APPLICATION_VND_MIF     = "application/vnd.mif";
	public static final String MIME_APPLICATION_VND_MSEXCEL   = "application/vnd.ms-excel";
	public static final String MIME_APPLICATION_VND_MSPOWERPOINT= "application/vnd.ms-powerpoint";
	public static final String MIME_APPLICATION_VND_RNREALMEDIA = "application/vnd.rn-realmedia";
	public static final String MIME_APPLICATION_X_BCPIO     = "application/x-bcpio";
	public static final String MIME_APPLICATION_X_CDLINK    = "application/x-cdlink";
	public static final String MIME_APPLICATION_X_CHESS_PGN   = "application/x-chess-pgn";
	public static final String MIME_APPLICATION_X_CPIO      = "application/x-cpio";
	public static final String MIME_APPLICATION_X_CSH     = "application/x-csh";
	public static final String MIME_APPLICATION_X_DIRECTOR    = "application/x-director";
	public static final String MIME_APPLICATION_X_DVI     = "application/x-dvi";
	public static final String MIME_APPLICATION_X_FUTURESPLASH  = "application/x-futuresplash";
	public static final String MIME_APPLICATION_X_GTAR      = "application/x-gtar";
	public static final String MIME_APPLICATION_X_HDF     = "application/x-hdf";
	public static final String MIME_APPLICATION_X_JAVASCRIPT  = "application/x-javascript";
	public static final String MIME_APPLICATION_X_KOAN      = "application/x-koan";
	public static final String MIME_APPLICATION_X_LATEX     = "application/x-latex";
	public static final String MIME_APPLICATION_X_NETCDF    = "application/x-netcdf";
	public static final String MIME_APPLICATION_X_OGG     = "application/x-ogg";
	public static final String MIME_APPLICATION_X_SH      = "application/x-sh";
	public static final String MIME_APPLICATION_X_SHAR      = "application/x-shar";
	public static final String MIME_APPLICATION_X_SHOCKWAVE_FLASH = "application/x-shockwave-flash";
	public static final String MIME_APPLICATION_X_STUFFIT     = "application/x-stuffit";
	public static final String MIME_APPLICATION_X_SV4CPIO     = "application/x-sv4cpio";
	public static final String MIME_APPLICATION_X_SV4CRC    = "application/x-sv4crc";
	public static final String MIME_APPLICATION_X_TAR       = "application/x-tar";
	public static final String MIME_APPLICATION_X_RAR_COMPRESSED= "application/x-rar-compressed";
	public static final String MIME_APPLICATION_X_TCL       = "application/x-tcl";
	public static final String MIME_APPLICATION_X_TEX       = "application/x-tex";
	public static final String MIME_APPLICATION_X_TEXINFO   = "application/x-texinfo";
	public static final String MIME_APPLICATION_X_TROFF     = "application/x-troff";
	public static final String MIME_APPLICATION_X_TROFF_MAN   = "application/x-troff-man";
	public static final String MIME_APPLICATION_X_TROFF_ME    = "application/x-troff-me";
	public static final String MIME_APPLICATION_X_TROFF_MS    = "application/x-troff-ms";
	public static final String MIME_APPLICATION_X_USTAR     = "application/x-ustar";
	public static final String MIME_APPLICATION_X_WAIS_SOURCE = "application/x-wais-source";
	public static final String MIME_APPLICATION_VND_MOZZILLA_XUL_XML = "application/vnd.mozilla.xul+xml";
	public static final String MIME_APPLICATION_XHTML_XML     = "application/xhtml+xml";
	public static final String MIME_APPLICATION_XSLT_XML    = "application/xslt+xml";
	public static final String MIME_APPLICATION_XML       = "application/xml";
	public static final String MIME_APPLICATION_XML_DTD     = "application/xml-dtd";
	public static final String MIME_IMAGE_BMP         = "image/bmp";
	public static final String MIME_IMAGE_CGM         = "image/cgm";
	public static final String MIME_IMAGE_GIF         = "image/gif";
	public static final String MIME_IMAGE_IEF         = "image/ief";
	public static final String MIME_IMAGE_JPEG          = "image/jpeg";
	public static final String MIME_IMAGE_TIFF          = "image/tiff";
	public static final String MIME_IMAGE_PNG         = "image/png";
	public static final String MIME_IMAGE_SVG_XML       = "image/svg+xml";
	public static final String MIME_IMAGE_VND_DJVU        = "image/vnd.djvu";
	public static final String MIME_IMAGE_WAP_WBMP        = "image/vnd.wap.wbmp";
	public static final String MIME_IMAGE_X_CMU_RASTER      = "image/x-cmu-raster";
	public static final String MIME_IMAGE_X_ICON        = "image/x-icon";
	public static final String MIME_IMAGE_X_PORTABLE_ANYMAP   = "image/x-portable-anymap";
	public static final String MIME_IMAGE_X_PORTABLE_BITMAP   = "image/x-portable-bitmap";
	public static final String MIME_IMAGE_X_PORTABLE_GRAYMAP  = "image/x-portable-graymap";
	public static final String MIME_IMAGE_X_PORTABLE_PIXMAP   = "image/x-portable-pixmap";
	public static final String MIME_IMAGE_X_RGB         = "image/x-rgb";
	public static final String MIME_AUDIO_BASIC         = "audio/basic";
	public static final String MIME_AUDIO_MIDI          = "audio/midi";
	public static final String MIME_AUDIO_MPEG          = "audio/mpeg";
	public static final String MIME_AUDIO_X_AIFF        = "audio/x-aiff";
	public static final String MIME_AUDIO_X_MPEGURL       = "audio/x-mpegurl";
	public static final String MIME_AUDIO_X_PN_REALAUDIO    = "audio/x-pn-realaudio";
	public static final String MIME_AUDIO_X_WAV         = "audio/x-wav";
	public static final String MIME_CHEMICAL_X_PDB        = "chemical/x-pdb";
	public static final String MIME_CHEMICAL_X_XYZ        = "chemical/x-xyz";
	public static final String MIME_MODEL_IGES          = "model/iges";
	public static final String MIME_MODEL_MESH          = "model/mesh";
	public static final String MIME_MODEL_VRLM          = "model/vrml";
	public static final String MIME_TEXT_PLAIN          = "text/plain";
	public static final String MIME_TEXT_RICHTEXT       = "text/richtext";
	public static final String MIME_TEXT_RTF          = "text/rtf";
	public static final String MIME_TEXT_HTML         = "text/html";
	public static final String MIME_TEXT_CALENDAR       = "text/calendar";
	public static final String MIME_TEXT_CSS          = "text/css";
	public static final String MIME_TEXT_SGML         = "text/sgml";
	public static final String MIME_TEXT_TAB_SEPARATED_VALUES = "text/tab-separated-values";
	public static final String MIME_TEXT_VND_WAP_XML      = "text/vnd.wap.wml";
	public static final String MIME_TEXT_VND_WAP_WMLSCRIPT    = "text/vnd.wap.wmlscript";
	public static final String MIME_TEXT_X_SETEXT       = "text/x-setext";
	public static final String MIME_TEXT_X_COMPONENT      = "text/x-component";
	public static final String MIME_VIDEO_QUICKTIME       = "video/quicktime";
	public static final String MIME_VIDEO_MPEG          = "video/mpeg";
	public static final String MIME_VIDEO_VND_MPEGURL     = "video/vnd.mpegurl";
	public static final String MIME_VIDEO_X_MSVIDEO       = "video/x-msvideo";
	public static final String MIME_VIDEO_X_MS_WMV        = "video/x-ms-wmv";
	public static final String MIME_VIDEO_X_SGI_MOVIE     = "video/x-sgi-movie";
	public static final String MIME_X_CONFERENCE_X_COOLTALK   = "x-conference/x-cooltalk";

	private final static HashMap<String, String> mimeTypeMapping;

	static {
		mimeTypeMapping = new HashMap<String, String>(200);
		registerMimeType("xul", MIME_APPLICATION_VND_MOZZILLA_XUL_XML);
		registerMimeType("json", MIME_APPLICATION_JSON);
		registerMimeType("ice", MIME_X_CONFERENCE_X_COOLTALK);
		registerMimeType("movie", MIME_VIDEO_X_SGI_MOVIE);
		registerMimeType("avi", MIME_VIDEO_X_MSVIDEO);
		registerMimeType("wmv", MIME_VIDEO_X_MS_WMV);
		registerMimeType("m4u", MIME_VIDEO_VND_MPEGURL);
		registerMimeType("mxu", MIME_VIDEO_VND_MPEGURL);
		registerMimeType("htc", MIME_TEXT_X_COMPONENT);
		registerMimeType("etx", MIME_TEXT_X_SETEXT);
		registerMimeType("wmls", MIME_TEXT_VND_WAP_WMLSCRIPT);
		registerMimeType("wml", MIME_TEXT_VND_WAP_XML);
		registerMimeType("tsv", MIME_TEXT_TAB_SEPARATED_VALUES);
		registerMimeType("sgm", MIME_TEXT_SGML);
		registerMimeType("sgml", MIME_TEXT_SGML);
		registerMimeType("css", MIME_TEXT_CSS);
		registerMimeType("ifb", MIME_TEXT_CALENDAR);
		registerMimeType("ics", MIME_TEXT_CALENDAR);
		registerMimeType("wrl", MIME_MODEL_VRLM);
		registerMimeType("vrlm", MIME_MODEL_VRLM);
		registerMimeType("silo", MIME_MODEL_MESH);
		registerMimeType("mesh", MIME_MODEL_MESH);
		registerMimeType("msh", MIME_MODEL_MESH);
		registerMimeType("iges", MIME_MODEL_IGES);
		registerMimeType("igs", MIME_MODEL_IGES);
		registerMimeType("rgb", MIME_IMAGE_X_RGB);
		registerMimeType("ppm", MIME_IMAGE_X_PORTABLE_PIXMAP);
		registerMimeType("pgm", MIME_IMAGE_X_PORTABLE_GRAYMAP);
		registerMimeType("pbm", MIME_IMAGE_X_PORTABLE_BITMAP);
		registerMimeType("pnm", MIME_IMAGE_X_PORTABLE_ANYMAP);
		registerMimeType("ico", MIME_IMAGE_X_ICON);
		registerMimeType("ras", MIME_IMAGE_X_CMU_RASTER);
		registerMimeType("wbmp", MIME_IMAGE_WAP_WBMP);
		registerMimeType("djv", MIME_IMAGE_VND_DJVU);
		registerMimeType("djvu", MIME_IMAGE_VND_DJVU);
		registerMimeType("svg", MIME_IMAGE_SVG_XML);
		registerMimeType("ief", MIME_IMAGE_IEF);
		registerMimeType("cgm", MIME_IMAGE_CGM);
		registerMimeType("bmp", MIME_IMAGE_BMP);
		registerMimeType("xyz", MIME_CHEMICAL_X_XYZ);
		registerMimeType("pdb", MIME_CHEMICAL_X_PDB);
		registerMimeType("ra", MIME_AUDIO_X_PN_REALAUDIO);
		registerMimeType("ram", MIME_AUDIO_X_PN_REALAUDIO);
		registerMimeType("m3u", MIME_AUDIO_X_MPEGURL);
		registerMimeType("aifc", MIME_AUDIO_X_AIFF);
		registerMimeType("aif", MIME_AUDIO_X_AIFF);
		registerMimeType("aiff", MIME_AUDIO_X_AIFF);
		registerMimeType("mp3", MIME_AUDIO_MPEG);
		registerMimeType("mp2", MIME_AUDIO_MPEG);
		registerMimeType("mp1", MIME_AUDIO_MPEG);
		registerMimeType("mpga", MIME_AUDIO_MPEG);
		registerMimeType("kar", MIME_AUDIO_MIDI);
		registerMimeType("mid", MIME_AUDIO_MIDI);
		registerMimeType("midi", MIME_AUDIO_MIDI);
		registerMimeType("dtd", MIME_APPLICATION_XML_DTD);
		registerMimeType("xsl", MIME_APPLICATION_XML);
		registerMimeType("xml", MIME_APPLICATION_XML);
		registerMimeType("xslt", MIME_APPLICATION_XSLT_XML);
		registerMimeType("xht", MIME_APPLICATION_XHTML_XML);
		registerMimeType("xhtml", MIME_APPLICATION_XHTML_XML);
		registerMimeType("src", MIME_APPLICATION_X_WAIS_SOURCE);
		registerMimeType("ustar", MIME_APPLICATION_X_USTAR);
		registerMimeType("ms", MIME_APPLICATION_X_TROFF_MS);
		registerMimeType("me", MIME_APPLICATION_X_TROFF_ME);
		registerMimeType("man", MIME_APPLICATION_X_TROFF_MAN);
		registerMimeType("roff", MIME_APPLICATION_X_TROFF);
		registerMimeType("tr", MIME_APPLICATION_X_TROFF);
		registerMimeType("t", MIME_APPLICATION_X_TROFF);
		registerMimeType("texi", MIME_APPLICATION_X_TEXINFO);
		registerMimeType("texinfo", MIME_APPLICATION_X_TEXINFO);
		registerMimeType("tex", MIME_APPLICATION_X_TEX);
		registerMimeType("tcl", MIME_APPLICATION_X_TCL);
		registerMimeType("sv4crc", MIME_APPLICATION_X_SV4CRC);
		registerMimeType("sv4cpio", MIME_APPLICATION_X_SV4CPIO);
		registerMimeType("sit", MIME_APPLICATION_X_STUFFIT);
		registerMimeType("swf", MIME_APPLICATION_X_SHOCKWAVE_FLASH);
		registerMimeType("shar", MIME_APPLICATION_X_SHAR);
		registerMimeType("sh", MIME_APPLICATION_X_SH);
		registerMimeType("cdf", MIME_APPLICATION_X_NETCDF);
		registerMimeType("nc", MIME_APPLICATION_X_NETCDF);
		registerMimeType("latex", MIME_APPLICATION_X_LATEX);
		registerMimeType("skm", MIME_APPLICATION_X_KOAN);
		registerMimeType("skt", MIME_APPLICATION_X_KOAN);
		registerMimeType("skd", MIME_APPLICATION_X_KOAN);
		registerMimeType("skp", MIME_APPLICATION_X_KOAN);
		registerMimeType("js", MIME_APPLICATION_X_JAVASCRIPT);
		registerMimeType("hdf", MIME_APPLICATION_X_HDF);
		registerMimeType("gtar", MIME_APPLICATION_X_GTAR);
		registerMimeType("spl", MIME_APPLICATION_X_FUTURESPLASH);
		registerMimeType("dvi", MIME_APPLICATION_X_DVI);
		registerMimeType("dxr", MIME_APPLICATION_X_DIRECTOR);
		registerMimeType("dir", MIME_APPLICATION_X_DIRECTOR);
		registerMimeType("dcr", MIME_APPLICATION_X_DIRECTOR);
		registerMimeType("csh", MIME_APPLICATION_X_CSH);
		registerMimeType("cpio", MIME_APPLICATION_X_CPIO);
		registerMimeType("pgn", MIME_APPLICATION_X_CHESS_PGN);
		registerMimeType("vcd", MIME_APPLICATION_X_CDLINK);
		registerMimeType("bcpio", MIME_APPLICATION_X_BCPIO);
		registerMimeType("rm", MIME_APPLICATION_VND_RNREALMEDIA);
		registerMimeType("ppt", MIME_APPLICATION_VND_MSPOWERPOINT);
		registerMimeType("mif", MIME_APPLICATION_VND_MIF);
		registerMimeType("grxml", MIME_APPLICATION_SRGS_XML);
		registerMimeType("gram", MIME_APPLICATION_SRGS);
		registerMimeType("smil", MIME_APPLICATION_RDF_SMIL);
		registerMimeType("smi", MIME_APPLICATION_RDF_SMIL);
		registerMimeType("rdf", MIME_APPLICATION_RDF_XML);
		registerMimeType("ogg", MIME_APPLICATION_X_OGG);
		registerMimeType("oda", MIME_APPLICATION_ODA);
		registerMimeType("dmg", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("lzh", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("so", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("lha", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("dms", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("bin", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("mathml", MIME_APPLICATION_MATHML_XML);
		registerMimeType("cpt", MIME_APPLICATION_MAC_COMPACTPRO);
		registerMimeType("hqx", MIME_APPLICATION_MAC_BINHEX40);
		registerMimeType("jnlp", MIME_APPLICATION_JNLP);
		registerMimeType("ez", MIME_APPLICATION_ANDREW_INSET);
		registerMimeType("txt", MIME_TEXT_PLAIN);
		registerMimeType("ini", MIME_TEXT_PLAIN);
		registerMimeType("c", MIME_TEXT_PLAIN);
		registerMimeType("h", MIME_TEXT_PLAIN);
		registerMimeType("cpp", MIME_TEXT_PLAIN);
		registerMimeType("cxx", MIME_TEXT_PLAIN);
		registerMimeType("cc", MIME_TEXT_PLAIN);
		registerMimeType("chh", MIME_TEXT_PLAIN);
		registerMimeType("java", MIME_TEXT_PLAIN);
		registerMimeType("csv", MIME_TEXT_PLAIN);
		registerMimeType("bat", MIME_TEXT_PLAIN);
		registerMimeType("cmd", MIME_TEXT_PLAIN);
		registerMimeType("asc", MIME_TEXT_PLAIN);
		registerMimeType("rtf", MIME_TEXT_RTF);
		registerMimeType("rtx", MIME_TEXT_RICHTEXT);
		registerMimeType("html", MIME_TEXT_HTML);
		registerMimeType("htm", MIME_TEXT_HTML);
		registerMimeType("zip", MIME_APPLICATION_ZIP);
		registerMimeType("rar", MIME_APPLICATION_X_RAR_COMPRESSED);
		registerMimeType("gzip", MIME_APPLICATION_X_GZIP);
		registerMimeType("gz", MIME_APPLICATION_X_GZIP);
		registerMimeType("tgz", MIME_APPLICATION_TGZ);
		registerMimeType("tar", MIME_APPLICATION_X_TAR);
		registerMimeType("gif", MIME_IMAGE_GIF);
		registerMimeType("jpeg", MIME_IMAGE_JPEG);
		registerMimeType("jpg", MIME_IMAGE_JPEG);
		registerMimeType("jpe", MIME_IMAGE_JPEG);
		registerMimeType("tiff", MIME_IMAGE_TIFF);
		registerMimeType("tif", MIME_IMAGE_TIFF);
		registerMimeType("png", MIME_IMAGE_PNG);
		registerMimeType("au", MIME_AUDIO_BASIC);
		registerMimeType("snd", MIME_AUDIO_BASIC);
		registerMimeType("wav", MIME_AUDIO_X_WAV);
		registerMimeType("mov", MIME_VIDEO_QUICKTIME);
		registerMimeType("qt", MIME_VIDEO_QUICKTIME);
		registerMimeType("mpeg", MIME_VIDEO_MPEG);
		registerMimeType("mpg", MIME_VIDEO_MPEG);
		registerMimeType("mpe", MIME_VIDEO_MPEG);
		registerMimeType("abs", MIME_VIDEO_MPEG);
		registerMimeType("doc", MIME_APPLICATION_MSWORD);
		registerMimeType("xls", MIME_APPLICATION_VND_MSEXCEL);
		registerMimeType("eps", MIME_APPLICATION_POSTSCRIPT);
		registerMimeType("ai", MIME_APPLICATION_POSTSCRIPT);
		registerMimeType("ps", MIME_APPLICATION_POSTSCRIPT);
		registerMimeType("pdf", MIME_APPLICATION_PDF);
		registerMimeType("exe", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("dll", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("class", MIME_APPLICATION_OCTET_STREAM);
		registerMimeType("jar", MIME_APPLICATION_JAVA_ARCHIVE);
	}

	public static final void registerMimeType(final String ext, final String mimeType) {
		mimeTypeMapping.put(ext, mimeType);
	}
	
	public static final String getMimeType(final String ext) {
		final String res = mimeTypeMapping.get(ext.trim().toLowerCase());
		if (res == null)
			return MIME_APPLICATION_OCTET_STREAM;
		return res;
	}
}
