package com.athena.backend.platform.dto.game;

public enum BetStatus {
	ACTIVE, 
	COMPLETED_WIN,
	COMPLETED_FAIL,
	COMPLETED_NO_ACTIVATION,
	PENDING_ACTIVATION, 
	REJECTED_INSUFFICENT_BALLANCE, 
	REJECTED_GAME_OUTOFDATE
}
